/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import javax.swing.table.DefaultTableModel;
import Modelos.Producto;
import Datos.FuncionesProductos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author eduardo
 */
public class PanelProductos extends javax.swing.JPanel {

    DefaultTableModel modeloTablaProductos = new DefaultTableModel();
    
    private void CargarColumnasProducto(){
       modeloTablaProductos.addColumn("num");
       modeloTablaProductos.addColumn("Descripcion");
       modeloTablaProductos.addColumn("Clave");
       modeloTablaProductos.addColumn("Precio");
       modeloTablaProductos.addColumn("Control de inventario");
       modeloTablaProductos.addColumn("Tipo de comida");
       modeloTablaProductos.addColumn("Cantidad");
       
       FuncionesProductos funcionesProductos = new FuncionesProductos();
       ArrayList<Producto> lista = funcionesProductos.MostrarProducto();
       
       int contador =lista.size();
       modeloTablaProductos.setNumRows(contador);
       for (int i = 0; i < contador; i++) {
            Producto producto = lista.get(i);
            modeloTablaProductos.setValueAt(producto.getId_producto(), i, 0);
            modeloTablaProductos.setValueAt(producto.getDescripcion(), i, 1);
            modeloTablaProductos.setValueAt(producto.getClave(), i, 2);
            modeloTablaProductos.setValueAt(producto.getPrecio(), i, 3);
            modeloTablaProductos.setValueAt(producto.getControl_inventario(), i, 4);
            modeloTablaProductos.setValueAt(producto.getId_tipo_comida(), i, 5);
            modeloTablaProductos.setValueAt(producto.getCantidad(), i, 6);
       }
       
       TableColumn columnaId = TablaProductos.getColumnModel().getColumn(0);
       columnaId.setMaxWidth(0);
       columnaId.setMinWidth(0);
       columnaId.setPreferredWidth(0);  
       
       TableColumn columnaControl = TablaProductos.getColumnModel().getColumn(4);
       columnaControl.setMaxWidth(0);
       columnaControl.setMinWidth(0);
       columnaControl.setPreferredWidth(0);  
       
       TableColumn columnaTipo = TablaProductos.getColumnModel().getColumn(5);
       columnaTipo.setMaxWidth(0);
       columnaTipo.setMinWidth(0);
       columnaTipo.setPreferredWidth(0);  
    }
    
    /**
     * Creates new form PanelUsuarios
     */
    public PanelProductos() {
        initComponents();
        CargarColumnasProducto();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEmpleados = new javax.swing.JPanel();
        lblTitulo3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDescripcionProducto = new javax.swing.JTextField();
        Porcentaje2 = new javax.swing.JLabel();
        btnLimpiarFormProductos = new javax.swing.JButton();
        btnGuardarProducto = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        lblIdProducto = new javax.swing.JLabel();
        lblEditandoProducto = new javax.swing.JLabel();
        Porcentaje3 = new javax.swing.JLabel();
        btnEliminarProducto = new javax.swing.JButton();
        cmbTipoProducto = new javax.swing.JComboBox<>();
        Porcentaje4 = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        txtClaveProducto = new javax.swing.JTextField();
        ckControlInventario = new javax.swing.JCheckBox();
        Porcentaje5 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        Porcentaje6 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelEmpleados.setBackground(new java.awt.Color(254, 254, 254));
        PanelEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo3.setText("Edicion de productos y consumibles");
        PanelEmpleados.add(lblTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1130, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("/images/dieta.png")); // NOI18N
        PanelEmpleados.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel9.setText("Tipo producto");
        PanelEmpleados.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 130, 40));
        PanelEmpleados.add(txtDescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 470, 40));

        Porcentaje2.setText("Descripcion");
        PanelEmpleados.add(Porcentaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 40));

        btnLimpiarFormProductos.setIcon(new javax.swing.ImageIcon("/images/limpiar.png")); // NOI18N
        btnLimpiarFormProductos.setText("Limpiar todo");
        btnLimpiarFormProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarFormProductosMouseClicked(evt);
            }
        });
        PanelEmpleados.add(btnLimpiarFormProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 230, 50));

        btnGuardarProducto.setIcon(new javax.swing.ImageIcon("/images/save.png")); // NOI18N
        btnGuardarProducto.setText("Guardar");
        btnGuardarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarProductoMouseClicked(evt);
            }
        });
        PanelEmpleados.add(btnGuardarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 50));
        PanelEmpleados.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 560, 10));

        TablaProductos.setModel(modeloTablaProductos);
        TablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaProductos);

        PanelEmpleados.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 510, 410));

        lblIdProducto.setText("0");
        PanelEmpleados.add(lblIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        lblEditandoProducto.setForeground(new java.awt.Color(251, 0, 0));
        lblEditandoProducto.setText("jLabel4");
        PanelEmpleados.add(lblEditandoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 80, 60, -1));

        Porcentaje3.setText("Clave");
        PanelEmpleados.add(Porcentaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 60, 40));

        btnEliminarProducto.setIcon(new javax.swing.ImageIcon("/images/eliminar.png")); // NOI18N
        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarProductoMouseClicked(evt);
            }
        });
        PanelEmpleados.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, 50));

        cmbTipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cajero", "Administrador" }));
        PanelEmpleados.add(cmbTipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 430, 40));

        Porcentaje4.setText("Precio");
        PanelEmpleados.add(Porcentaje4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 60, 40));
        PanelEmpleados.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 180, 40));
        PanelEmpleados.add(txtClaveProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 180, 40));

        ckControlInventario.setText("Control de inventario");
        PanelEmpleados.add(ckControlInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        Porcentaje5.setText("Cantidad");
        PanelEmpleados.add(Porcentaje5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 80, 40));
        PanelEmpleados.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 150, 40));

        Porcentaje6.setText("Buscar");
        PanelEmpleados.add(Porcentaje6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 80, 40));
        PanelEmpleados.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 330, 40));

        btnBuscarProducto.setIcon(new javax.swing.ImageIcon("/images/lupa.png")); // NOI18N
        btnBuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarProductoMouseClicked(evt);
            }
        });
        PanelEmpleados.add(btnBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1056, 100, 50, 60));

        add(PanelEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarFormProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFormProductosMouseClicked
        
    }//GEN-LAST:event_btnLimpiarFormProductosMouseClicked

    private void btnGuardarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarProductoMouseClicked
        
    }//GEN-LAST:event_btnGuardarProductoMouseClicked

    private void TablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductosMouseClicked
        
    }//GEN-LAST:event_TablaProductosMouseClicked

    private void btnEliminarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProductoMouseClicked
        
    }//GEN-LAST:event_btnEliminarProductoMouseClicked

    private void btnBuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProductoMouseClicked
        
    }//GEN-LAST:event_btnBuscarProductoMouseClicked

    private void LimpiarFormularioProducto(){
        
    }

    /*
    *private void LimpiarFormularioEmpleado(){
        txtCodigoEmpleado.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        lblIdEmpleado.setText(""+0);
        
        modeloTablaEmpleado.setRowCount(0);
        modeloTablaEmpleado.setColumnCount(0);
        CargarColumnasEmpleado();
        
        lblEditandoEmpleado.setVisible(false);
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEmpleados;
    private javax.swing.JLabel Porcentaje2;
    private javax.swing.JLabel Porcentaje3;
    private javax.swing.JLabel Porcentaje4;
    private javax.swing.JLabel Porcentaje5;
    private javax.swing.JLabel Porcentaje6;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnGuardarProducto;
    private javax.swing.JButton btnLimpiarFormProductos;
    private javax.swing.JCheckBox ckControlInventario;
    private javax.swing.JComboBox<String> cmbTipoProducto;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblEditandoProducto;
    private javax.swing.JLabel lblIdProducto;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtClaveProducto;
    private javax.swing.JTextField txtDescripcionProducto;
    private javax.swing.JTextField txtPrecioProducto;
    // End of variables declaration//GEN-END:variables
}
