/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import javax.swing.table.DefaultTableModel;
import Modelos.Producto;
import Modelos.TipoProducto;
import Datos.FuncionesProductos;
import Datos.FuncionesTipoProducto;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author eduardo
 */
public class PanelProductos extends javax.swing.JPanel {

    DefaultTableModel modeloTablaProductos = new DefaultTableModel();
    DefaultComboBoxModel <TipoProducto> modeloComboTipoProducto;
    
    private void CargarColumnasProducto(){
       modeloTablaProductos.addColumn("num");
       modeloTablaProductos.addColumn("Descripcion");
       modeloTablaProductos.addColumn("Clave");
       modeloTablaProductos.addColumn("Precio");
       modeloTablaProductos.addColumn("Control de inventario");
       modeloTablaProductos.addColumn("Tipo de comida");
       modeloTablaProductos.addColumn("Cantidad");
       
       FuncionesProductos funcionesProductos = new FuncionesProductos();
       ArrayList<Producto> lista = funcionesProductos.MostrarProducto();
       
       int contador =lista.size();
       modeloTablaProductos.setNumRows(contador);
       for (int i = 0; i < contador; i++) {
            Producto producto = lista.get(i);
            modeloTablaProductos.setValueAt(producto.getId_producto(), i, 0);
            modeloTablaProductos.setValueAt(producto.getDescripcion(), i, 1);
            modeloTablaProductos.setValueAt(producto.getClave(), i, 2);
            modeloTablaProductos.setValueAt(producto.getPrecio(), i, 3);
            modeloTablaProductos.setValueAt(producto.getControl_inventario(), i, 4);
            modeloTablaProductos.setValueAt(producto.getId_tipo_comida(), i, 5);
            modeloTablaProductos.setValueAt(producto.getCantidad(), i, 6);
       }
       
       TableColumn columnaId = TablaProductos.getColumnModel().getColumn(0);
       columnaId.setMaxWidth(0);
       columnaId.setMinWidth(0);
       columnaId.setPreferredWidth(0);  
       
       TableColumn columnaControl = TablaProductos.getColumnModel().getColumn(4);
       columnaControl.setMaxWidth(0);
       columnaControl.setMinWidth(0);
       columnaControl.setPreferredWidth(0);  
       
       TableColumn columnaTipo = TablaProductos.getColumnModel().getColumn(5);
       columnaTipo.setMaxWidth(0);
       columnaTipo.setMinWidth(0);
       columnaTipo.setPreferredWidth(0);  
    }
    
    private void CargarTipoCategorias(){
        FuncionesTipoProducto funcionesTipoProducto = new FuncionesTipoProducto();
        ArrayList<TipoProducto> lista;
        lista = funcionesTipoProducto.MostrarTipoProducto();
        
        for (TipoProducto tipoProd:lista) {
            modeloComboTipoProducto.addElement(tipoProd);
        }
    }
    
    /**
     * Creates new form PanelUsuarios
     */
    public PanelProductos() {
        modeloComboTipoProducto = new DefaultComboBoxModel<TipoProducto>();
        initComponents();
        CargarColumnasProducto();
        CargarTipoCategorias();
        lblEditandoProducto.setVisible(false);
        lblIdProducto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEmpleados = new javax.swing.JPanel();
        lblTitulo3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDescripcionProducto = new javax.swing.JTextField();
        Porcentaje2 = new javax.swing.JLabel();
        btnLimpiarFormProductos = new javax.swing.JButton();
        btnGuardarProducto = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        lblIdProducto = new javax.swing.JLabel();
        lblEditandoProducto = new javax.swing.JLabel();
        Porcentaje3 = new javax.swing.JLabel();
        btnEliminarProducto = new javax.swing.JButton();
        cmbTipoProducto = new javax.swing.JComboBox<>();
        Porcentaje4 = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        txtClaveProducto = new javax.swing.JTextField();
        ckControlInventario = new javax.swing.JCheckBox();
        Porcentaje5 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        Porcentaje6 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelEmpleados.setBackground(new java.awt.Color(254, 254, 254));
        PanelEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo3.setText("Edicion de productos y consumibles");
        PanelEmpleados.add(lblTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1130, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("/images/dieta.png")); // NOI18N
        PanelEmpleados.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel9.setText("Tipo producto");
        PanelEmpleados.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 130, 40));
        PanelEmpleados.add(txtDescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 470, 40));

        Porcentaje2.setText("Descripcion");
        PanelEmpleados.add(Porcentaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 40));

        btnLimpiarFormProductos.setIcon(new javax.swing.ImageIcon("/images/limpiar.png")); // NOI18N
        btnLimpiarFormProductos.setText("Limpiar todo");
        btnLimpiarFormProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarFormProductosMouseClicked(evt);
            }
        });
        btnLimpiarFormProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFormProductosActionPerformed(evt);
            }
        });
        PanelEmpleados.add(btnLimpiarFormProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 230, 50));

        btnGuardarProducto.setIcon(new javax.swing.ImageIcon("/images/save.png")); // NOI18N
        btnGuardarProducto.setText("Guardar");
        btnGuardarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarProductoMouseClicked(evt);
            }
        });
        PanelEmpleados.add(btnGuardarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 50));
        PanelEmpleados.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 560, 10));

        TablaProductos.setModel(modeloTablaProductos);
        TablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaProductos);

        PanelEmpleados.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 510, 410));

        lblIdProducto.setText("0");
        PanelEmpleados.add(lblIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        lblEditandoProducto.setForeground(new java.awt.Color(251, 0, 0));
        lblEditandoProducto.setText("jLabel4");
        PanelEmpleados.add(lblEditandoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 80, 420, -1));

        Porcentaje3.setText("Clave");
        PanelEmpleados.add(Porcentaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 60, 40));

        btnEliminarProducto.setIcon(new javax.swing.ImageIcon("/images/eliminar.png")); // NOI18N
        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarProductoMouseClicked(evt);
            }
        });
        PanelEmpleados.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, 50));

        cmbTipoProducto.setModel(modeloComboTipoProducto );
        PanelEmpleados.add(cmbTipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 430, 40));

        Porcentaje4.setText("Precio");
        PanelEmpleados.add(Porcentaje4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 60, 40));
        PanelEmpleados.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 180, 40));
        PanelEmpleados.add(txtClaveProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 180, 40));

        ckControlInventario.setText("Control de inventario");
        PanelEmpleados.add(ckControlInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        Porcentaje5.setText("Cantidad");
        PanelEmpleados.add(Porcentaje5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 80, 40));
        PanelEmpleados.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 150, 40));

        Porcentaje6.setText("Buscar");
        PanelEmpleados.add(Porcentaje6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 80, 40));
        PanelEmpleados.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 330, 40));

        btnBuscarProducto.setIcon(new javax.swing.ImageIcon("/images/lupa.png")); // NOI18N
        btnBuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarProductoMouseClicked(evt);
            }
        });
        PanelEmpleados.add(btnBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1056, 100, 50, 60));

        add(PanelEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarFormProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFormProductosMouseClicked
        LimpiarFormularioProducto();
    }//GEN-LAST:event_btnLimpiarFormProductosMouseClicked

    private void btnGuardarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarProductoMouseClicked
        String descripcion = txtDescripcionProducto.getText().trim();
        String clave = txtClaveProducto.getText().trim();
        Double precio = Double.parseDouble(txtPrecioProducto.getText().trim());
        int control_inventario;
        if (ckControlInventario.isSelected()) {
            control_inventario = 1;
        }else{
            control_inventario=0;
        }
        int cantidad =  Integer.parseInt(txtCantidad.getText().trim());
        
        TipoProducto tipoProducto = (TipoProducto)cmbTipoProducto.getSelectedItem();
        int idTipoProducto = tipoProducto.getId();
        
        
        Producto producto = new Producto(Integer.parseInt(lblIdProducto.getText().trim()), descripcion, clave, precio, control_inventario, idTipoProducto, cantidad);
        
        FuncionesProductos funcionesProductos = new FuncionesProductos();
        
        if (Integer.parseInt(lblIdProducto.getText()) == 0) {
            if (funcionesProductos.GuardarProducto(producto)) {
                JOptionPane.showMessageDialog(null,"Se ha registrado correctamente el producto "+ descripcion +" con la clave "+clave);
                LimpiarFormularioProducto();
            }else{
                 JOptionPane.showMessageDialog(null, "No se ha podido guardar la informacion, verifique la informacion","Error!", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            if (funcionesProductos.ActualizarProducto(producto)) {
                JOptionPane.showMessageDialog(null,"Se ha actualizado correctamente la informacion del producto "+ descripcion);
                LimpiarFormularioProducto();
            }else{
                JOptionPane.showMessageDialog(null, "No se ha podido guardar la informacion, verifique la informacion","Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarProductoMouseClicked

    private void TablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductosMouseClicked
        int index = TablaProductos.getSelectedRow();
        TableModel model = TablaProductos.getModel();
        
        int id = Integer.parseInt(model.getValueAt(index,0).toString());
        String descripcion = model.getValueAt(index,1).toString();
        String clave = model.getValueAt(index,2).toString();
        double precio = Double.parseDouble(model.getValueAt(index,3).toString());
        int control_inventario;
        if (Integer.parseInt(model.getValueAt(index,4).toString())==1) {
            ckControlInventario.setSelected(true);
        }
        else{
            ckControlInventario.setSelected(false);
        }
        int tipo_producto=Integer.parseInt(model.getValueAt(index,5).toString());
        
        int numItems = cmbTipoProducto.getItemCount();
        
        for (int i = 0; i < numItems; i++) {
            TipoProducto producto = modeloComboTipoProducto.getElementAt(i);
            if (producto.getId()==tipo_producto) {
                cmbTipoProducto.setSelectedIndex(i);
            }
        }
        
        int cantidad = Integer.parseInt(model.getValueAt(index,6).toString());
        
        lblIdProducto.setText(""+id);
        txtDescripcionProducto.setText(descripcion);
        txtClaveProducto.setText(clave);
        txtPrecioProducto.setText(""+precio);
        txtCantidad.setText(""+cantidad);
        //cmbTipoProducto.setSelectedItem("Comida");
        
        lblEditandoProducto.setVisible(true);
        lblEditandoProducto.setText("Editando informacion de "+descripcion);
    }//GEN-LAST:event_TablaProductosMouseClicked

    private void btnEliminarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProductoMouseClicked
        FuncionesProductos funcionesProductos = new FuncionesProductos();
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "¿Desea eliminar el producto "+txtDescripcionProducto.getText().trim());
        
        if(dialogResult == JOptionPane.YES_OPTION){
            if (funcionesProductos.EliminarProducto(Integer.parseInt(lblIdProducto.getText()))) {
                JOptionPane.showMessageDialog(null,"Se ha eliminado correctamente el usuario ");
                LimpiarFormularioProducto();
            }else{
                JOptionPane.showMessageDialog(null, "No es posible eliminar el tipo de precio","Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarProductoMouseClicked

    private void btnBuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProductoMouseClicked
        if (txtBuscarProducto.getText()!="") {
            modeloTablaProductos.setRowCount(0);
            modeloTablaProductos.setColumnCount(0);
            
            modeloTablaProductos.addColumn("num");
            modeloTablaProductos.addColumn("Descripcion");
            modeloTablaProductos.addColumn("Clave");
            modeloTablaProductos.addColumn("Precio");
            modeloTablaProductos.addColumn("Control de inventario");
            modeloTablaProductos.addColumn("Tipo de comida");
            modeloTablaProductos.addColumn("Cantidad");

            FuncionesProductos funcionesProductos = new FuncionesProductos();
            ArrayList<Producto> lista = funcionesProductos.BuscarProducto(txtBuscarProducto.getText().trim());

            int contador =lista.size();
            modeloTablaProductos.setNumRows(contador);
            for (int i = 0; i < contador; i++) {
                 Producto producto = lista.get(i);
                 modeloTablaProductos.setValueAt(producto.getId_producto(), i, 0);
                 modeloTablaProductos.setValueAt(producto.getDescripcion(), i, 1);
                 modeloTablaProductos.setValueAt(producto.getClave(), i, 2);
                 modeloTablaProductos.setValueAt(producto.getPrecio(), i, 3);
                 modeloTablaProductos.setValueAt(producto.getControl_inventario(), i, 4);
                 modeloTablaProductos.setValueAt(producto.getId_tipo_comida(), i, 5);
                 modeloTablaProductos.setValueAt(producto.getCantidad(), i, 6);
            }

            TableColumn columnaId = TablaProductos.getColumnModel().getColumn(0);
            columnaId.setMaxWidth(0);
            columnaId.setMinWidth(0);
            columnaId.setPreferredWidth(0);  

            TableColumn columnaControl = TablaProductos.getColumnModel().getColumn(4);
            columnaControl.setMaxWidth(0);
            columnaControl.setMinWidth(0);
            columnaControl.setPreferredWidth(0);  

            TableColumn columnaTipo = TablaProductos.getColumnModel().getColumn(5);
            columnaTipo.setMaxWidth(0);
            columnaTipo.setMinWidth(0);
            columnaTipo.setPreferredWidth(0);  
        }
    }//GEN-LAST:event_btnBuscarProductoMouseClicked

    private void btnLimpiarFormProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFormProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarFormProductosActionPerformed

    private void LimpiarFormularioProducto(){
        txtDescripcionProducto.setText("");
        txtClaveProducto.setText("");
        txtPrecioProducto.setText("");
        txtCantidad.setText("");
        ckControlInventario.setSelected(false);
        cmbTipoProducto.setSelectedIndex(0);
        
        modeloTablaProductos.setRowCount(0);
        modeloTablaProductos.setColumnCount(0);
        CargarColumnasProducto(); 
        
        lblIdProducto.setText(""+0);
        lblEditandoProducto.setVisible(false);
    }

    /*
    *private void LimpiarFormularioEmpleado(){
        txtCodigoEmpleado.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        lblIdEmpleado.setText(""+0);
        
        modeloTablaEmpleado.setRowCount(0);
        modeloTablaEmpleado.setColumnCount(0);
        CargarColumnasEmpleado();
        
        lblEditandoEmpleado.setVisible(false);
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEmpleados;
    private javax.swing.JLabel Porcentaje2;
    private javax.swing.JLabel Porcentaje3;
    private javax.swing.JLabel Porcentaje4;
    private javax.swing.JLabel Porcentaje5;
    private javax.swing.JLabel Porcentaje6;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnGuardarProducto;
    private javax.swing.JButton btnLimpiarFormProductos;
    private javax.swing.JCheckBox ckControlInventario;
    private javax.swing.JComboBox<TipoProducto> cmbTipoProducto;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblEditandoProducto;
    private javax.swing.JLabel lblIdProducto;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtClaveProducto;
    private javax.swing.JTextField txtDescripcionProducto;
    private javax.swing.JTextField txtPrecioProducto;
    // End of variables declaration//GEN-END:variables
}
