/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;
import Datos.FuncionesFormaDePago;
import Datos.FuncionesProductos;
import Datos.FuncionesTipoPrecio;
import Modelos.FormaDePago;
import Modelos.TipoDePrecio;
import Modelos.Venta;
import Modelos.DetalleVenta;
import Modelos.Producto;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author eduardo
 */
public class PanelVentas extends javax.swing.JPanel {
    DefaultComboBoxModel <FormaDePago> modeloComboFormaDePago;
    DefaultComboBoxModel <TipoDePrecio> modeloComboTipoPrecio;

    private void CargarFormaDePago(){
        FuncionesFormaDePago funcionesFormaDePago = new FuncionesFormaDePago();
        ArrayList<FormaDePago> lista;
        lista = funcionesFormaDePago.MostrarFormaDePago();
        
        for (FormaDePago formaDePago:lista) {
            modeloComboFormaDePago.addElement(formaDePago);
        }
    }
    
    private void CargarTipoDePrecio(){
        FuncionesTipoPrecio funcionesTipoPrecio = new FuncionesTipoPrecio();
        ArrayList<TipoDePrecio> listaTipoPrecio;
        listaTipoPrecio = funcionesTipoPrecio.MostrarTipoPrecio();
        
        for (TipoDePrecio tipoDePrecio:listaTipoPrecio) {
            modeloComboTipoPrecio.addElement(tipoDePrecio);
        }
    }
    
    /**
     * Creates new form PanelVentas
     */
    public PanelVentas() {
        modeloComboFormaDePago = new DefaultComboBoxModel<FormaDePago>();
        modeloComboTipoPrecio = new DefaultComboBoxModel<TipoDePrecio>();
        CargarFormaDePago();
        CargarTipoDePrecio();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo3 = new javax.swing.JLabel();
        PanelCajero = new javax.swing.JPanel();
        lblTitulo4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        lblPrecioProducto = new javax.swing.JLabel();
        btnBuscarProducto = new javax.swing.JButton();
        btnLimpiarFormulario = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbTiposDePrecio = new javax.swing.JComboBox<>();
        cmbFormasDePago = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCodigoEmpleado = new javax.swing.JTextField();
        btnReimprimirTicket = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblSumaProductos = new javax.swing.JLabel();
        lblTotalFinal = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        btnCobrar = new javax.swing.JButton();
        lblTotalProducto = new javax.swing.JLabel();
        btnQuitarProducto = new javax.swing.JButton();
        lblIdProducto = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        txtCantidadProducto = new javax.swing.JSpinner();
        lblTotalProducto1 = new javax.swing.JLabel();

        lblTitulo3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo3.setText("Edicion de productos y consumibles");

        PanelCajero.setBackground(new java.awt.Color(254, 254, 254));
        PanelCajero.setPreferredSize(new java.awt.Dimension(1146, 618));
        PanelCajero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo4.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        lblTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo4.setText("Cajero");
        PanelCajero.add(lblTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 860, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 25, 25));
        jLabel6.setText("Logo empresa");
        PanelCajero.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 120, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("/images/empresa.png")); // NOI18N
        PanelCajero.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/images/cafeteria.png")); // NOI18N
        PanelCajero.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 24, 80, 90));

        jLabel2.setText("Tipo de precio");
        PanelCajero.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 120, 40));

        txtCodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoProductoKeyPressed(evt);
            }
        });
        PanelCajero.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 120, 40));

        lblPrecioProducto.setText("[Precio]");
        PanelCajero.add(lblPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, 40));

        btnBuscarProducto.setIcon(new javax.swing.ImageIcon("/images/buscar.png")); // NOI18N
        btnBuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarProductoMouseClicked(evt);
            }
        });
        PanelCajero.add(btnBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, 40));

        btnLimpiarFormulario.setIcon(new javax.swing.ImageIcon("/images/limpiar.png")); // NOI18N
        btnLimpiarFormulario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarFormularioMouseClicked(evt);
            }
        });
        PanelCajero.add(btnLimpiarFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 360, 50, 40));

        jLabel4.setText("Cantidad");
        PanelCajero.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 70, 40));

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaProductos);

        PanelCajero.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 820, 160));

        jLabel7.setText("Codigo producto");
        PanelCajero.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 140, 40));

        jLabel8.setText("Total a pagar");
        PanelCajero.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 120, 40));

        cmbTiposDePrecio.setModel(modeloComboTipoPrecio );
        PanelCajero.add(cmbTiposDePrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 260, 40));

        cmbFormasDePago.setModel(modeloComboFormaDePago);
        PanelCajero.add(cmbFormasDePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 260, 40));

        jLabel9.setText("Codigo empleado");
        PanelCajero.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, -1, 20));
        PanelCajero.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 120, 10));

        txtCodigoEmpleado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelCajero.add(txtCodigoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, 120, 40));

        btnReimprimirTicket.setIcon(new javax.swing.ImageIcon("/images/impresora.png")); // NOI18N
        btnReimprimirTicket.setText("Reimprimir ticket");
        btnReimprimirTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReimprimirTicketMouseClicked(evt);
            }
        });
        PanelCajero.add(btnReimprimirTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 280, 60));

        jLabel10.setText("Forma de pago");
        PanelCajero.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 120, 40));

        jLabel11.setText("Suma");
        PanelCajero.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 50, 40));

        lblSumaProductos.setText("[SUMA]");
        PanelCajero.add(lblSumaProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, 240, 40));

        lblTotalFinal.setText("[TOTAL PAGA]");
        PanelCajero.add(lblTotalFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, 230, 40));

        btnAgregarProducto.setIcon(new javax.swing.ImageIcon("/images/anadir-al-carrito.png")); // NOI18N
        btnAgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProductoMouseClicked(evt);
            }
        });
        PanelCajero.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, 40));

        btnCobrar.setIcon(new javax.swing.ImageIcon("/images/dinero-en-efectivo.png")); // NOI18N
        btnCobrar.setText("Cobrar");
        btnCobrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCobrarMouseClicked(evt);
            }
        });
        PanelCajero.add(btnCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 280, 60));

        lblTotalProducto.setText("Total");
        PanelCajero.add(lblTotalProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 60, -1));

        btnQuitarProducto.setIcon(new javax.swing.ImageIcon("/images/quitar-del-carrito.png")); // NOI18N
        btnQuitarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitarProductoMouseClicked(evt);
            }
        });
        PanelCajero.add(btnQuitarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 300, 50, 50));

        lblIdProducto.setText("idProd");
        PanelCajero.add(lblIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        lblNombreProducto.setText("[Nombre de producto]");
        PanelCajero.add(lblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        txtCantidadProducto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtCantidadProductoStateChanged(evt);
            }
        });
        txtCantidadProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCantidadProductoMouseClicked(evt);
            }
        });
        PanelCajero.add(txtCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 120, 40));

        lblTotalProducto1.setText("Total");
        PanelCajero.add(lblTotalProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCajero, javax.swing.GroupLayout.DEFAULT_SIZE, 1154, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProductoMouseClicked
        FormBusquedaProductos formBusquedaProductos = new FormBusquedaProductos();
        formBusquedaProductos.setVisible(true);
    }//GEN-LAST:event_btnBuscarProductoMouseClicked

    private void btnLimpiarFormularioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFormularioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarFormularioMouseClicked

    private void btnReimprimirTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReimprimirTicketMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReimprimirTicketMouseClicked

    private void btnAgregarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProductoMouseClicked

    private void btnCobrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCobrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCobrarMouseClicked

    private void btnQuitarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitarProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitarProductoMouseClicked

    private void txtCodigoProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProductoKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_DOWN) {
            FuncionesProductos funcionesProductos = new FuncionesProductos();
            ArrayList<Producto> lista=funcionesProductos.BuscarProductoPorCodigo(txtCodigoProducto.getText().trim());
            int contador =lista.size();
            for (int i = 0; i < contador; i++) {
                Producto producto = lista.get(i);
                txtCodigoProducto.setText(""+producto.getClave());
                lblIdProducto.setText(""+producto.getId_producto());
                lblNombreProducto.setText(producto.getDescripcion());
                lblPrecioProducto.setText(""+producto.getPrecio());
                txtCantidadProducto.setValue(1);
                lblTotalProducto.setText(""+producto.getPrecio());
            }
        }
        
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            JOptionPane.showMessageDialog(this,"Añadir a tabla");
        }
        
        //Limpiar si esta vacio
        if (evt.getKeyCode()==KeyEvent.VK_BACK_SPACE && txtCodigoProducto.getText().equals("")) {
            lblIdProducto.setText("");
            lblNombreProducto.setText("");
            lblPrecioProducto.setText("");
            txtCantidadProducto.setValue(1);
            lblTotalProducto.setText("");
        }
        
    }//GEN-LAST:event_txtCodigoProductoKeyPressed

    private void txtCantidadProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadProductoMouseClicked
        
    }//GEN-LAST:event_txtCantidadProductoMouseClicked

    private void txtCantidadProductoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtCantidadProductoStateChanged
        int valor = (int) txtCantidadProducto.getValue();
        if (valor==0) {
            txtCantidadProducto.setValue(1);
            valor = 1;
        }
        
        double precio = Double.parseDouble(lblPrecioProducto.getText());
        lblTotalProducto.setText(""+precio*valor);
    }//GEN-LAST:event_txtCantidadProductoStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCajero;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnLimpiarFormulario;
    private javax.swing.JButton btnQuitarProducto;
    private javax.swing.JButton btnReimprimirTicket;
    private javax.swing.JComboBox<FormaDePago> cmbFormasDePago;
    private javax.swing.JComboBox<TipoDePrecio> cmbTiposDePrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lblIdProducto;
    public static javax.swing.JLabel lblNombreProducto;
    public static javax.swing.JLabel lblPrecioProducto;
    private javax.swing.JLabel lblSumaProductos;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblTotalFinal;
    public static javax.swing.JLabel lblTotalProducto;
    public static javax.swing.JLabel lblTotalProducto1;
    public static javax.swing.JSpinner txtCantidadProducto;
    private javax.swing.JTextField txtCodigoEmpleado;
    public static javax.swing.JTextField txtCodigoProducto;
    // End of variables declaration//GEN-END:variables
}
