/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import javax.swing.table.DefaultTableModel;
import Modelos.Usuario;
import Datos.FuncionesUsuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author eduardo
 */
public class PanelUsuarios extends javax.swing.JPanel {

    DefaultTableModel modeloTablaUsuario = new DefaultTableModel();
    
    private void CargarColumnasUsuario(){
       modeloTablaUsuario.addColumn("num");
       modeloTablaUsuario.addColumn("Nombres");
       modeloTablaUsuario.addColumn("Apellidos");
       modeloTablaUsuario.addColumn("Email");
       modeloTablaUsuario.addColumn("Tipo de usuario");
       
       FuncionesUsuario funcionesUsuario = new FuncionesUsuario();
       ArrayList<Usuario> lista = funcionesUsuario.MostrarUsuario();
       
       int contador =lista.size();
       modeloTablaUsuario.setNumRows(contador);
       for (int i = 0; i < contador; i++) {
            Usuario user = lista.get(i);
            modeloTablaUsuario.setValueAt(user.getId_usuario(), i, 0);
            modeloTablaUsuario.setValueAt(user.getNombres(), i, 1);
            modeloTablaUsuario.setValueAt(user.getApellidos(), i, 2);
            modeloTablaUsuario.setValueAt(user.getClave(), i, 3);
            modeloTablaUsuario.setValueAt(user.getTipo_usuario(), i, 4);
       }
       
       TableColumn columna = TablaUsuarios.getColumnModel().getColumn(0);
       columna.setMaxWidth(0);
       columna.setMinWidth(0);
       columna.setPreferredWidth(0);
       
    }
    /**
     * Creates new form PanelUsuarios
     */
    public PanelUsuarios() {
        initComponents();
        CargarColumnasUsuario();
        lblEditandoUsuario.setVisible(false);
        lblIdUser.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEmpleados = new javax.swing.JPanel();
        lblTitulo3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombresUsuario = new javax.swing.JTextField();
        Porcentaje2 = new javax.swing.JLabel();
        txtApellidosUsuario = new javax.swing.JTextField();
        btnLimpiarFormUsuario = new javax.swing.JButton();
        btnGuardarUsuario = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        lblIdUser = new javax.swing.JLabel();
        lblEditandoUsuario = new javax.swing.JLabel();
        Porcentaje3 = new javax.swing.JLabel();
        txtCorreoUsuario = new javax.swing.JTextField();
        btnEliminarUsuario = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtPasswordUsuario = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        cmbTipoDeUsuario = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelEmpleados.setBackground(new java.awt.Color(254, 254, 254));
        PanelEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo3.setText("Edicion de usuarios de sistema");
        PanelEmpleados.add(lblTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1130, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("/images/users.png")); // NOI18N
        PanelEmpleados.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel9.setText("Tipo de usuario");
        PanelEmpleados.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 130, 40));
        PanelEmpleados.add(txtNombresUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 330, 40));

        Porcentaje2.setText("Nombres");
        PanelEmpleados.add(Porcentaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, 40));
        PanelEmpleados.add(txtApellidosUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 330, 40));

        btnLimpiarFormUsuario.setIcon(new javax.swing.ImageIcon("/images/limpiar.png")); // NOI18N
        btnLimpiarFormUsuario.setText("Limpiar todo");
        btnLimpiarFormUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarFormUsuarioMouseClicked(evt);
            }
        });
        PanelEmpleados.add(btnLimpiarFormUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 230, 50));

        btnGuardarUsuario.setIcon(new javax.swing.ImageIcon("/images/save.png")); // NOI18N
        btnGuardarUsuario.setText("Guardar");
        btnGuardarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarUsuarioMouseClicked(evt);
            }
        });
        PanelEmpleados.add(btnGuardarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, 50));
        PanelEmpleados.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 460, 10));

        TablaUsuarios.setModel(modeloTablaUsuario);
        TablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaUsuarios);

        PanelEmpleados.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 570, 430));

        lblIdUser.setText("0");
        PanelEmpleados.add(lblIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        lblEditandoUsuario.setForeground(new java.awt.Color(251, 0, 0));
        lblEditandoUsuario.setText("jLabel4");
        PanelEmpleados.add(lblEditandoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 80, 60, -1));

        Porcentaje3.setText("Apellidos");
        PanelEmpleados.add(Porcentaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 40));
        PanelEmpleados.add(txtCorreoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 330, 40));

        btnEliminarUsuario.setIcon(new javax.swing.ImageIcon("/images/eliminar.png")); // NOI18N
        btnEliminarUsuario.setText("Eliminar");
        btnEliminarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarUsuarioMouseClicked(evt);
            }
        });
        PanelEmpleados.add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, 50));

        jLabel10.setText("Correo electronico");
        PanelEmpleados.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 160, 40));
        PanelEmpleados.add(txtPasswordUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 330, 40));

        jLabel11.setText("Contraseña");
        PanelEmpleados.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 110, 40));

        cmbTipoDeUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cajero", "Administrador" }));
        PanelEmpleados.add(cmbTipoDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 330, 40));

        add(PanelEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarFormUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarFormUsuarioMouseClicked
        LimpiarFormularioUsuarios();
    }//GEN-LAST:event_btnLimpiarFormUsuarioMouseClicked

    private void btnGuardarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarUsuarioMouseClicked
        String nombres = txtNombresUsuario.getText().trim();
        String apellidos = txtApellidosUsuario.getText().trim();
        String email = txtCorreoUsuario.getText().trim();
        String password = txtPasswordUsuario.getText().trim();
        String tipoUsuario = cmbTipoDeUsuario.getSelectedItem().toString(); //
        
        Usuario user = new Usuario(Integer.parseInt(lblIdUser.getText()),nombres,apellidos,email,password,tipoUsuario);
        FuncionesUsuario funcionesUsuario = new FuncionesUsuario();
        
        if (Integer.parseInt(lblIdUser.getText()) == 0) {
            if (funcionesUsuario.GuardarUsuario(user)) {
                JOptionPane.showMessageDialog(null,"Se ha registrado correctamente el usuario "+nombres+" "+apellidos+" con el correo"+email);
                LimpiarFormularioUsuarios();
            }else{
                 JOptionPane.showMessageDialog(null, "No se ha podido guardar la informacion, verifique la informacion","Error!", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            if (funcionesUsuario.ActualizarUsuario(user)) {
                JOptionPane.showMessageDialog(null,"Se ha actualizado correctamente la informacion del usuario "+nombres+" "+apellidos);
                LimpiarFormularioUsuarios();
            }else{
                JOptionPane.showMessageDialog(null, "No se ha podido guardar la informacion, verifique la informacion","Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarUsuarioMouseClicked

    private void TablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUsuariosMouseClicked
        int index = TablaUsuarios.getSelectedRow();
        TableModel model = TablaUsuarios.getModel();
        
        int id = Integer.parseInt(model.getValueAt(index,0).toString());
        String nombres = model.getValueAt(index,1).toString();
        String apellidos = model.getValueAt(index,2).toString();
        String email = model.getValueAt(index,3).toString();
        String tipo_usuario = model.getValueAt(index,4).toString();
        
        lblIdUser.setText(""+id);
        txtNombresUsuario.setText(nombres);
        txtApellidosUsuario.setText(apellidos);
        txtCorreoUsuario.setText(email);
        
        if (tipo_usuario.equals("Cajero")) {
            cmbTipoDeUsuario.setSelectedIndex(0);
        }else{
            cmbTipoDeUsuario.setSelectedIndex(1);
        }
        
        lblEditandoUsuario.setVisible(true);
        lblEditandoUsuario.setText("Editando informacion de "+nombres+" "+apellidos);
    }//GEN-LAST:event_TablaUsuariosMouseClicked

    private void btnEliminarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioMouseClicked
        FuncionesUsuario funcionesUsuario = new FuncionesUsuario();
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "¿Desea eliminar el usuario "+txtCorreoUsuario.getText()+"?","Advertencia",dialogButton);
        
        if(dialogResult == JOptionPane.YES_OPTION){
            if (funcionesUsuario.EliminarUsuario(Integer.parseInt(lblIdUser.getText()))) {
                JOptionPane.showMessageDialog(null,"Se ha eliminado correctamente el usuario ");
                LimpiarFormularioUsuarios();
            }else{
                JOptionPane.showMessageDialog(null, "No es posible eliminar el tipo de precio","Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarUsuarioMouseClicked

    private void LimpiarFormularioUsuarios(){
        txtNombresUsuario.setText("");
        txtApellidosUsuario.setText("");
        txtCorreoUsuario.setText("");
        txtPasswordUsuario.setText("");
        lblEditandoUsuario.setVisible(false);
        lblIdUser.setText(""+0);
        cmbTipoDeUsuario.setSelectedIndex(0);
        
        modeloTablaUsuario.setRowCount(0);
        modeloTablaUsuario.setColumnCount(0);
        CargarColumnasUsuario();
        
    }

    /*
    *private void LimpiarFormularioEmpleado(){
        txtCodigoEmpleado.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        lblIdEmpleado.setText(""+0);
        
        modeloTablaEmpleado.setRowCount(0);
        modeloTablaEmpleado.setColumnCount(0);
        CargarColumnasEmpleado();
        
        lblEditandoEmpleado.setVisible(false);
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEmpleados;
    private javax.swing.JLabel Porcentaje2;
    private javax.swing.JLabel Porcentaje3;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnGuardarUsuario;
    private javax.swing.JButton btnLimpiarFormUsuario;
    private javax.swing.JComboBox<String> cmbTipoDeUsuario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblEditandoUsuario;
    private javax.swing.JLabel lblIdUser;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JTextField txtApellidosUsuario;
    private javax.swing.JTextField txtCorreoUsuario;
    private javax.swing.JTextField txtNombresUsuario;
    private javax.swing.JPasswordField txtPasswordUsuario;
    // End of variables declaration//GEN-END:variables
}
